SQUARE_SIZE = 5.0
SPIRAL_STEP = 1.0
DEFAULT_ALTITUDE = 1.7
CALIBRATION_DISTANCE = 5.0
WAIT_BEFORE_START = 2.0

TIMEOUT_SEARCH = 10.0
TIMEOUT_DESCEND = 12.0
TIMEOUT_MARKER_LOST = 5.0
TIMEOUT_MARKER_LOST_MOVEMENT = 4.0
TIMEOUT_POINT_REACHED = 2.0

STABILIZE_TIME = 2.0
DESCENT_TIMEOUT = 10.0

MIN_CENTERING_STEP = 0.05
MAX_CENTERING_STEP = 0.3
CENTERING_TOLERANCE_X = 100
CENTERING_TOLERANCE_Y = 100
CENTERING_PAUSE_BEFORE = 5.0
CENTERING_PAUSE_AFTER = 10.0
CENTERING_MAX_ATTEMPTS = 20
CENTERING_DESCENT_ALTITUDE = 1.5
HEIGHT_STEP = 0.02
POST_CENTERING_PAUSE = 2.0

DEAD_ZONE_X = 20.0
DEAD_ZONE_Y = 20.0
SPEED_CENTERING = 0.02
REQUIRED_STABLE_FRAMES = 3
DESCEND_SPEED = 0.08
HOVER_DURATION = 5.0
